# Generated by Django 5.2 on 2025-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customrequest_alter_city_image_alter_country_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.AddField(
            model_name='city',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
