# Generated by Django 5.2 on 2025-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tour_images_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
