# Generated by Django 5.2 on 2025-04-20 09:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='flight',
        ),
        migrations.AddField(
            model_name='application',
            name='flight_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_back', to='api.flight'),
        ),
        migrations.AddField(
            model_name='application',
            name='flight_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_to', to='api.flight'),
        ),
        migrations.AddField(
            model_name='application',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
