# Generated by Django 5.2 on 2025-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tour_flight_application_flight_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='flight_back',
        ),
        migrations.RemoveField(
            model_name='application',
            name='flight_to',
        ),
        migrations.AddField(
            model_name='application',
            name='flights_back',
            field=models.ManyToManyField(blank=True, related_name='applications_back', to='api.flight'),
        ),
        migrations.AddField(
            model_name='application',
            name='flights_to',
            field=models.ManyToManyField(blank=True, related_name='applications_to', to='api.flight'),
        ),
    ]
