# Generated by Django 5.2 on 2025-04-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_flight_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='images',
        ),
    ]
