# Generated by Django 5.2 on 2025-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_tour_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
