# Generated by Django 5.2 on 2025-04-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_application_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
